[package]
authors = ["omnect@conplement.de>"]
description = "This tool provides a command-line interface to configure omnect-os images and to communicate with omnect-os empowered devices."
edition = "2021"
homepage = "https://www.omnect.io/home"
license = "MIT OR Apache-2.0"
name = "omnect-cli"
readme = "README.md"
repository = "https://github.com/omnect/omnect-cli"
version = "0.17.2"

[dependencies]
actix-web = "4.4"
anyhow = "1"
bzip2 = "0.4"
clap = { version = "4.0", features = ["derive"] }
directories = "5.0"
env_logger = "0.8"
filemagic = "0.12"
flate2 = "1.0"
omnect-crypto = { git = "https://github.com/omnect/omnect-crypto.git", tag = "0.4.0" }
keyring = "2.0"
lazy_static = "1.4"
log = "0.4"
num_cpus = "1.13"
oauth2 = "4.4"
open = "4.1"
regex = "1.5.5"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_path_to_error = "0.1"
stdext = "0.3"
strum = "0.25"
strum_macros = "0.25"
tokio = { version = "1", features = [
    "macros",
    "io-std",
    "io-util",
    "fs",
    "net",
] }
toml = "0.8"
uuid = { version = "0.8", default-features = false, features = ["v4"] }
url = { version = "2.4", feature = ["serde"] }
validator = { version = "0.14", features = ["derive"] }
xz2 = "0.1"

[dev-dependencies]
httpmock = "0.6"
file_diff = "1.0"
assert_cmd = "2.0"

# metadata for building with cargo-deb (https://crates.io/crates/cargo-deb) 
[package.metadata.deb]
depends = "bmap-tools, e2tools, fdisk, keychain, libc6 (>= 2.34), libmagic1, libssl3 (>= 3.0.0), mtools"
revision = ""